services:
  - type: web
    name: ddp-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd myproject && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "cd myproject && gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ddp-database
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: ddp-database
    databaseName: ddp_db
    plan: free
